version: "3"

volumes:
  db_data:
  app_code:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}
#  logs:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ${PWD}/logs

services:
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:alpine
    restart: on-failure
    ports:
      # To avoid conflicts with default Nginx configuration we bind our app to 81 port
      - ${NGINX_PORT}:81
    volumes:
#      - logs:/etc/logs
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - app_code:/var/www/html:rw
    environment:
      NGINX_HOST: nginx
      NGINX_PORT: 81
    links:
      - fpm

  fpm:
    container_name: ${PROJECT_NAME}_fpm
#    image: themiju/php:2018-09-25
    build: .
    restart: on-failure
#    ports:
#      - ${XDEBUG_PORT}:${XDEBUG_REMOTE_PORT}
    environment:
      # For PHPStorm: should match server name in Settings / Preferences | Languages & Frameworks | PHP | Servers
      PHP_IDE_CONFIG: "serverName=${PHP_IDE_SERVERNAME}"
      XDEBUG_CONFIG: "
        remote_port=${XDEBUG_REMOTE_PORT}
        remote_host=${XDEBUG_REMOTE_HOST}
      "
    volumes:
      - app_code:/var/www/html:rw
#      - logs:/logs:rw
    links:
      - db

  db:
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    container_name: ${PROJECT_NAME}_mysql
    image: mysql:8
    restart: on-failure
    ports:
      - 127.0.0.1:${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    #      - ./mysql.cnf:/etc/mysql/mysql.conf.d/zz-mysqld.cnf
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  adminer:
    container_name: ${PROJECT_NAME}_adminer
    image: adminer
    restart: on-failure
    ports:
      - ${ADMINER_PORT}:8080
    links:
      - db
