POST localhost:2222/api/product
Accept: application/json
Content-Type: application/json

{
  "color":  "white",
  "price": "1220",
  "size": "L",
  "type": "cup"
}

###

GET localhost:2222/api/order/3/calculate
Accept: application/json
Content-Type: application/json

###

GET localhost:2222/api/order?limit=71&offset=0&product_type=car
Accept: application/json
Content-Type: application/json

###

GET https://ipapi.co/213.221.63.94/json

###

POST localhost:2222/api/order/1/place
Accept: application/json
Content-Type: application/json

###
